### ISSUE TITLE
[TODO] Database optimizations

### ISSUE THREAD

**Issue by TheAlpha16** [TheAlpha16/isolet#32]
**component: **database

- [x] consider creating materialized view for scoreboard aggregation
- [ ] maybe create a separate table for team members
- [x] separate solved from teams table 
- [x] separate uhints from teams table
- [ ] replace expiry triggers with cron jobs

**Comment by TheAlpha16** [comment]
revamped database schema completely, issues became irrelevant
