### ISSUE TITLE
[TODO] New UI 

### ISSUE THREAD

**Issue by TheAlpha16** [TheAlpha16/isolet#33]
**component**: ui-new

- [x] make navbar responsive
- [x] timer does not update when window is not in focus
- [ ] alignment issues in challenge name overflow in challenge card
